# Generated by Django 2.0.1 on 2018-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, choices=[('T', 'Tank'), ('R', 'Room')], max_length=1, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('redeemed', models.DateTimeField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(blank=True)),
            ],
        ),
    ]
