# Generated by Django 2.0.1 on 2018-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_validto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='redeemed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='validto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
