# Generated by Django 2.0.1 on 2018-04-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180424_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
